version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:latest

    steps:
      - checkout
      - run:
          name: "Build a binary"
          command: make build

  test:
    docker:
      - image: circleci/golang:latest

    steps:
      - checkout
      - run:
          name: "Run tests"
          command: make test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
