global:
  smtp_smarthost: mail.example.com:25
  smtp_from: prometheus@example.com

route:
  receiver: 'default'
  routes:
  - receiver: 'executor'
    match:
      alertname: RebootMachine

receivers:
- name: 'default'
  email_configs:
  - to: ops@example.com

- name: 'executor'
  webhook_configs:
  - url: http://localhost:8080
